<?php

acf_add_local_field_group(array(
	'key' => 'group_5e5e5aed93efe',
	'title' => 'Опции',
	'fields' => array(
		array(
			'key' => 'field_5e5e5b0cab95d',
			'label' => 'Основные',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'wpml_cf_preferences' => 0,
		),
		array(
			'key' => 'field_5e5e5b1eab95e',
			'label' => 'Название сайта',
			'name' => 'site_name',
			'type' => 'text',
			'instructions' => 'Используется в title',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.333',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e5e5b98ab95f',
			'label' => 'Краткое описание сайта',
			'name' => 'site_descr',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.333',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e5e5bbbab960',
			'label' => 'Имя приложения',
			'name' => 'app_name',
			'type' => 'text',
			'instructions' => 'Имя приложения (Progressive Web App). Если оставить пустым будет использоваться название сайта.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.333',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e5e5c31ab962',
			'label' => 'Пользовательский код в тег header',
			'name' => 'add_code_header',
			'type' => 'textarea',
			'instructions' => 'Используется для добавление пользовательских стилей, скриптов, токенов, например для подключения Google Search Console, Google Analytics...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => 'Пример: "<script>console.log(\'Testing additional code in header\');</script>"',
			'maxlength' => '',
			'rows' => 14,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e5e5c5eab963',
			'label' => 'Пользовательский код перед закрытием body',
			'name' => 'add_code_footer',
			'type' => 'textarea',
			'instructions' => 'Используется для добавление пользовательских стилей, скриптов в конце страницы',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 0,
			'default_value' => '',
			'placeholder' => 'Пример: "<script>console.log(\'Testing additional code in footer\');</script>"',
			'maxlength' => '',
			'rows' => 14,
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => get_translated_page_id_by_slug('options'),
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));
